line_length:
  warning: 200
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

file_length:
  ignore_comment_only_lines: true

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  excluded: [id]